name: CICD Pipeline 

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn compile

    - name: Notify Slack (Compile)
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: job,commit,repo,ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build_project:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build Project
      run: mvn package

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar

    - name: Notify Slack (Build)
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: job,commit,repo,ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  docker_login:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: ./app

    - name: Docker login
      uses: docker/login-action@3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy JAR to root for Docker build
      run: cp ./app/*.jar ./app.jar

    - name: Build Docker image
      run: docker build -t hacked01/app-jar:latest .

    - name: Push Docker image
      run: docker push hacked01/app-jar:latest

    - name: List running containers
      run: docker ps

    - name: Notify Slack (Docker)
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: job,commit,repo,ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
